### ISSUE TITLE
add game feedback in graphical main window

### ISSUE THREAD

**Issue by christianparpart** [keithoma/NewLanguagePlus#7]
Draw method that takes game engine as const ref and also draws each players points as small think bars at top or bottom

each goal represents a coloured bar, i.e. if left player scored 3 out of 8 goals in order to win, there shall be 3 coloured and 5 grayed bars.

same for right player.

should we draw a win-screen? (maybe in year 2020)

**Comment by keithoma** [comment]
implemented
